# Generated by Django 4.1.7 on 2023-03-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
