# Generated by Django 4.1.7 on 2023-03-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('email', models.CharField(default='1459576020@qq.com', max_length=20, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
