# Generated by Django 4.1.7 on 2023-03-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_equipment_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, verbose_name='购买日期'),
        ),
    ]
