# Generated by Django 4.1.7 on 2023-03-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_equipment_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='空闲中', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='users',
            name='manage',
            field=models.BooleanField(default=False, verbose_name='管理员'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='租赁编号')),
                ('rent_time', models.DateField(auto_now_add=True, verbose_name='租赁时间')),
                ('return_time', models.DateField(auto_now=True, verbose_name='归还时间')),
                ('status', models.CharField(default='未归还', max_length=20, verbose_name='状态')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
