# Generated by Django 4.1.7 on 2023-03-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_equipment_count_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='img_url',
            field=models.ImageField(default=111, upload_to='img_url/', verbose_name='图片地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='img_url',
            field=models.ImageField(default=111, upload_to='img_url/', verbose_name='图片地址'),
            preserve_default=False,
        ),
    ]
