# Generated by Django 4.1.7 on 2023-03-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_equipment_img_url_users_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='introduce',
            field=models.TextField(default=123, verbose_name='设备描述'),
            preserve_default=False,
        ),
    ]
